#### The assessment questions are designed in such a way where the user will use NumPy functions and create a python function(def) to solve each question.
#### 1)  1. Write a function, foo_1, that takes a NumPy array `arr` and returns the indices of the elements that are closest to a given target. If target is not in the given array, it should return ‘no item found’

In [1]:
import numpy as np

In [2]:
def foo_1(arr, target):
   
    if target not in arr:
        return 'no item found'
    
    differences = np.abs(arr - target)
    closest_indices = np.argsort(differences)
    return closest_indices

In [3]:
# Example - 1:
arr1 = np.array([3, 8, 7, 7, 7, 7, 7, 8, 7, 10])
target1 = 7
result1 = foo_1(arr1, target1)
print(result1)

[2 3 4 5 6 8 1 7 9 0]


In [4]:
# Example - 2:
arr2 = np.array([3, 8, 7, 7, 7, 7, 7, 8, 7, 10])
target2 = 11
result2 = foo_1(arr2, target2)
print(result2)

no item found


#### explaination
* step - 1  firstly, Check if target is in the array if not it returns 'no item found'
* step - 2  if target is present Calculate the absolute differences between each element and the target
* step - 3  then find the indices of the minimum differences by using the 'np.argsort'
* step - 4 The result is an array of indices indicating the positions of elements closest to the target.

#### 2) Write a user defined function foo_2 that takes a  2,3 dim NumPy array arr and returns a new n-1 dim array, where each element is replaced by the count of non-zero elements wrt axis.

In [5]:
def foo_2(arr, axis):
    if arr.ndim not in [2, 3]:
        raise ValueError("Input array must be 2D or 3D")

    count_nonzero = np.count_nonzero(arr, axis=axis)
    
    if axis == 0:
        return count_nonzero
    elif axis == 1:
        return count_nonzero
    elif axis == 2 and arr.ndim == 3:
        return count_nonzero
    else:
        raise ValueError("Invalid axis value for the given array")

In [6]:
# By Using Example-1:
arr = np.array([[1, 2, 3, 4],
                [0, 5, 0, 0],
                [2, 0, 1, 0]])

# Test cases-1
output_axis_0 = foo_2(arr, axis=0)
print("Output for axis=0:", output_axis_0)

output_axis_1 = foo_2(arr, axis=1)
print("Output for axis=1:", output_axis_1)

Output for axis=0: [2 2 2 1]
Output for axis=1: [4 1 2]


In [7]:
# By Using Example-2:
arr1 = np.array([[[1, 2, 3, 4],
                  [0, 5, 0, 0],
                  [2, 0, 1, 0]],
                 [[2, 0, 1, 0],
                  [0, 5, 0, 0],
                  [1, 2, 3, 4]]])

# Test cases-2
output_axis_2 = foo_2(arr1, axis=0)
print("\nOutput for axis=0 (for 3D array):")
print(output_axis_2)

output_axis_3 = foo_2(arr1, axis=1)
print("\nOutput for axis=1 (for 3D array):")
print(output_axis_3)

output_axis_4 = foo_2(arr1, axis=2)
print("\nOutput for axis=2 (for 3D array):")
print(output_axis_4)


Output for axis=0 (for 3D array):
[[2 1 2 1]
 [0 2 0 0]
 [2 1 2 1]]

Output for axis=1 (for 3D array):
[[2 2 2 1]
 [2 2 2 1]]

Output for axis=2 (for 3D array):
[[4 1 2]
 [2 1 4]]


#### Explaination
* step-1 This function takes a 2D or 3D NumPy array
* step-2 taking an axis as input and returns a new array where each element is replaced by the count of non-zero elements along the specified axis. 
* step-3 The example demonstrates how to use the function with different axes and input arrays.

#### 3.3.1 You are given a 2D NumPy array of data representing student scores. Each row represents a student, and each column represents a subject. Extract the scores of all students who scored above 90 in at least one subject. Provide the resulting array.

In [8]:
data = np.array([[85, 89, 88],
                 [78, 89, 94],
                 [91, 87, 90],
                 [87, 95, 84]])

mask = np.any(data > 90, axis=1)

result = data[mask]
print(result)

[[78 89 94]
 [91 87 90]
 [87 95 84]]


#### Explaination
* step-1 defining the 2D array: creates a 2D NumPy array named data, where each row represents a student, and each column represents a subject. The array holds the scores of students in various subjects.
* step-2 Create a Boolean Mask: Here, a boolean mask is created using the condition 'data > 90'. This condition generates a boolean array of the same shape as 'data', where each element is 'True' if the corresponding element in 'data' is greater than 90 and 'False' otherwise. The 'np.any(..., axis=1)' function is then applied along axis 1 (columns) to check if there is at least one 'True' value in each row. The result is a boolean array (mask) indicating whether each student scored above 90 in at least one subject.
* step-3 Filtering the Data Using the Mask: The boolean mask, 'mask' is used to filter the rows of the original array 'data'. Only the rows (students) corresponding to 'True' values in the mask are included in the result.
* step -4 Print the Result: Finally, the resulting array (scores of students who scored above 90 in at least one subject) is printed to the console.

>In summary, the code efficiently extracts and prints the scores of students who scored above 90 in at least one subject using NumPy's boolean indexing and array manipulation capabilities.

#### 3.3.2 You are provided with a 2D NumPy array of data representing sales data for different products. Each row corresponds to a product, and each column represents the monthly sales for a specific month. Calculate the following statistics for each product: mean, median, standard deviation, and the month with the highest sales.

In [9]:
data = np.array([[120, 150, 130, 110],
                 [200, 180, 220, 250],
                 [90, 100, 95, 110],
                 [300, 280, 320, 340]])

mean_values = np.mean(data, axis=1) # Calculate mean along axis 1 (columns)
median_values = np.median(data, axis=1) # Calculate median along axis 1 (columns)
std_dev_values = np.std(data, axis=1) # Calculate standard deviation along axis 1 (columns)

max_month_indices = np.argmax(data, axis=1) # Finding the month with the highest sales along axis 1 (columns)
max_sales_months = ['Month {}'.format(month + 1) for month in max_month_indices]

# results
for i in range(data.shape[0]):
    print(f"Product {i + 1}:")
    print(f"  Mean: {mean_values[i]}")
    print(f"  Median: {median_values[i]}")
    print(f"  Standard Deviation: {std_dev_values[i]}")
    print(f"  Month with the Highest Sales: {max_sales_months[i]}")
    print()

Product 1:
  Mean: 127.5
  Median: 125.0
  Standard Deviation: 14.79019945774904
  Month with the Highest Sales: Month 2

Product 2:
  Mean: 212.5
  Median: 210.0
  Standard Deviation: 25.8602010819715
  Month with the Highest Sales: Month 4

Product 3:
  Mean: 98.75
  Median: 97.5
  Standard Deviation: 7.39509972887452
  Month with the Highest Sales: Month 4

Product 4:
  Mean: 310.0
  Median: 310.0
  Standard Deviation: 22.360679774997898
  Month with the Highest Sales: Month 4



#### Explaination
* using NumPy functions to calculate the mean, median, standard deviation, and the month with the highest sales for each product.
* axis=1 is used to perform the calculations along columns (monthly sales)
* np.argmax is used to find the index of the maximum value along the specified axis (month with the highest sales). 
* The results are then printed for each product.

#### 3.3.3 Create a NumPy array of size 1000 with random integers between 1 and 100. Then, use NumPy functions to find the top 10 most frequently occurring values in the array.

In [10]:
random_array = np.random.randint(1, 101, size=1000)
print(random_array)

unique_values, counts = np.unique(random_array, return_counts=True)
sorted_indices = np.argsort(-counts)
sorted_values = unique_values[sorted_indices]
sorted_counts = counts[sorted_indices]

print("Top 10 most frequently occurring values:")
for i in range(10):
    print(f"{sorted_values[i]}: {sorted_counts[i]} occurrences")


[ 11  97  64   5   7   5  40  87  58  61  12  33   9  43  35  37  12  95
  87  69  18  10  15  73  26  25   5  18  27  22  64  93  64  45  81  63
  81  17  69  10  64   2  29   7  84  35  49  51  42  33  58  65  35  59
  54  41  14  78  22  52  71  95   6  13  22   7  66   5  48   7  55  40
  87   3  10  65  67  74  23  21  33 100  92  85  21  58  44  86  19  89
  33  62  33  98   9   3  80  41  80  77  58  33  85  43  73  76  15  48
   3  93  81   6  88  16  86  67  73  51  47  71  64  81   5  23  35  76
  61  87  23  15  76  14  51  27  51  55  93  72  75  80  57  42  26  54
  42  77  35  24  93  97   7  91  57  26   4  69  65  31  78  52  29  80
  70  60  12  58  18  90  50   9  72  55  43  10  45  68  11  68  75   2
  52  41  94  48  75  26  40  91  85  35  61  50   7   7  22  86  98  11
  85  30  73  25  53  21  85  19  56  51  56  13  83  17  84   3  41  69
  51  30   9  52  45  27  71  90  84  76  83  77  74  69  12  27  87  34
  23  92  30  80   9  84  92  17   4  55  33  46  5

#### Explanation
1) Creating a NumPy array with random integers between 1 and 100
2) Use NumPy's unique function to get unique values and their counts
3) Sort the unique values based on their counts in descending order
4) Displayed the top 10 most frequently occurring values